### ISSUE TITLE
Double/Single quote issue.

### ISSUE THREAD

**Issue by andyherbert** [ansilove/BlockZone#1]
I've started using BlockZone over on [blocktronics.tumblr.com](http://blocktronics.tumblr.com/), and I've noticed that Tumblr, in order to produce good typography, is converting the double and single quotes to 'curly-quotes'.

![screen shot 2015-02-02 at 18 53 15](https://cloud.githubusercontent.com/assets/25620/6006775/07663708-ab0d-11e4-83fa-d3a08d573bcb.png)

This is pretty typical of MarkDown-type parsers, but it's spoiling the intended aesthetic of the site. I propose copying the codepage 437 glyphs to the code points for the curly quotes, but I wanted to get the blessing to do it first, before I update the repo.

**Comment by ByteProject** [comment]
Hey, since the last release, your name is mentioned as copyright holder too :D 

Yeah sure, great idea. If changes to the font add improvements there is no need to talk about the matter, including requests as above and also adding extra glyphs to other codepages that mimic the classic DOS look and feel, fixes, whatever. So feel free :)

BTW: BlockZone over at Blocktronics? Awesome!

**Comment by ByteProject** [comment]
Please don't forget to update the font version number and also please update the version number in the README.

**Comment by andyherbert** [comment]
Affirmative.

**Comment by andyherbert** [comment]
Strangely enough, bumping the version number is the only problem I'm having with FontForge.

Are you changing it here?

![screen shot 2015-02-02 at 19 27 35](https://cloud.githubusercontent.com/assets/25620/6007501/888a37da-ab12-11e4-9665-74236ccb7141.png)

Because whenever I re-generate the fonts and then re-open, it always re-appears as 1.003. Everything else works as expected (including the sfnt revision, whatever that is). Presumably I'm doing something wrong, but I'm wondering how you did it.

**Comment by ByteProject** [comment]
Well - FontForge is a great font editor but a bit behind when it comes to properly naming and versioning fonts. It does not support the Mac strings for example, relevant for displaying current version number on OS X. It does not let you alter the font description either, at least I have found no way to do it like in expensive editors. 

I'm using a free tool called Typelight to change version information. Here is how you do it with Typlight which is pretty straightforward.

Open BlockZone in Typelight. In Menu, select --> Font --> Description.

![screen shot 2015-02-02 at 20 45 38](https://cloud.githubusercontent.com/assets/153544/6007699/77653e1e-ab1c-11e4-8c06-600cee705e1a.png)

Hit Enter after you changed it and press okay. 

Go to Menu --> Font --> Names

![screen shot 2015-02-02 at 20 47 56](https://cloud.githubusercontent.com/assets/153544/6007749/e77631f4-ab1c-11e4-8a05-21ca5cccb173.png)

and hit "Advanced". Change the font version here as well and hit OK.

![screen shot 2015-02-02 at 20 50 32](https://cloud.githubusercontent.com/assets/153544/6007791/3313ec32-ab1d-11e4-89b1-141fda718c34.png)

Stay in the basic font Name menu and select "Macintosh Roman" on the bottom.

![screen shot 2015-02-02 at 20 51 13](https://cloud.githubusercontent.com/assets/153544/6007809/57135be0-ab1d-11e4-9c39-a5536edac6d9.png)

Now go to "Advanced" again. Check "Copy English (US)" which will copy the string updates to the Mac Font Names. This will cause to show the correct version number and updated information when investigating the font in Finder on OS X with CMD+i 

![screen shot 2015-02-02 at 20 53 11](https://cloud.githubusercontent.com/assets/153544/6007883/c9efe32c-ab1d-11e4-9740-eb0bcc33226b.png)

That's it. :)

**Comment by andyherbert** [comment]
I just downloaded TypeLight, and I've notice that it's an installable pkg, which requires my administrator password to install, and no indication on what is being installed and where. Unfortunately this goes against my personal policy of installing software on my machine that perform this practise.
I am prepared to push the change to the ReadMe and updated font, sans-version number, so if you're prepared to change the version number then we can do it that way.

**Comment by ByteProject** [comment]
Uhm... what the hell? Not sure if I installed it back then, I don't think so as I tend being allergic to such a behavior as well. Went to the developer website and it seems he doesn't share the Mac and Linux versions of TypeLight anymore, so not sure where you DL'ed it. I just zipped it and sent you an DM with the DL-Link on Twitter. Could you please check if that works for you? If not I'm gonna update the version numbers myself. :)

**Comment by andyherbert** [comment]
Done.

**Comment by ByteProject** [comment]
Awesome!
